
language: node_js
node_js:
    - "4.5"
script: node_modules/karma/bin/karma start my.config.js --single-run
#script: node_modules/karma/bin/karma start karma.config.js --single-run




before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
    - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash

deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: petajuda
