language: python
python:
- "2.7"

addons:
  sauce_connect: true
	 username: $SauceLogin
  	 access_key: $SauceAccessKey
script: python test/travis-testcases.py


deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: petajuda
