language: python
python:
  - "2.7"


#install:
  #- pip install sauceclient 
#  - pip install selenium nose #--use-mirrors  

#script: nosetests

addons:
  sauce_connect:
    username: $SauceLogin
    access_key: $SauceAcessKey


script: nosetests

deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: petajuda