language: python
python:
    - "2.7"

//before_script:
//- python RunFlask.py worker.py &
//- python worker.py &
script: python test/travis-testcases.py
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: petajuda
