language: python
python:
    - '2.7'
env:
  global:
    - secure: $SauceLogin
    - secure: $SauceAccessKey
addons:
  sauce_connect: true
services:
    - redis-server
//before_script:
//- python RunFlask.py worker.py &
//- python worker.py &
script: python test/travis-testcases.py
branches:
  only:
    - master
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: petajuda
